# Generated by Django 4.2.19 on 2025-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_alter_category_options_alter_submission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="submission",
            name="execution_time",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="started_at",
        ),
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="best_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(max_length=20),
        ),
    ]
