# Generated by Django 4.2.19 on 2025-02-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0004_alter_userprogress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="template",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="test_cases",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="time_limit",
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("cpp", "C++"),
                ],
                default="python",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="earned_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
