# Generated by Django 4.2.19 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_remove_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="feedback",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["challenge", "user", "status"],
                name="challenges__challen_75ba76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["challenge", "status", "score"],
                name="challenges__challen_3f58de_idx",
            ),
        ),
    ]
