# Generated by Django 4.2.19 on 2025-02-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "challenges",
            "0006_alter_submission_feedback_alter_submission_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="submission",
            name="challenges__challen_75ba76_idx",
        ),
        migrations.RemoveIndex(
            model_name="submission",
            name="challenges__challen_3f58de_idx",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="score",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="best_score",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.URLField(
                default="https://example.com/default-achievement-icon.png"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="content",
            field=models.TextField(help_text="Challenge content in Markdown format"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="template",
            field=models.TextField(
                blank=True, help_text="Initial code template for the challenge"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="test_cases",
            field=models.JSONField(
                default=list, help_text="List of test cases for programming challenges"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="time_limit",
            field=models.IntegerField(default=3600, help_text="Time limit in seconds"),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="earned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
