# Generated by Django 4.2.19 on 2025-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0009_userprogress_attempts_userprogress_best_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="draft_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
