# Generated by Django 4.2.19 on 2025-02-20 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0010_userprogress_draft_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="draft_code",
        ),
    ]
