# Generated by Django 4.2.19 on 2025-02-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_username",
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(default="python", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
